version: "3"

volumes:
    prometheus:
    grafana:

services:
  prometheus:
      image: prom/prometheus:latest
      # container_name: monitoring_prometheus
      restart: unless-stopped
      volumes:
        - ./prometheus-config:/etc/prometheus
        - prometheus:/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
      # expose:
      #   - 9090
      ports:
        - 9090:9090
      links:
        - cadvisor:cadvisor
        - node-exporter:node-exporter
      deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints:
            - node.role == manager
        resources:
          limits:
            memory: 2048M
          reservations:
            memory: 128M

  node-exporter:
      image: prom/node-exporter:latest
      # container_name: monitoring_node_exporter
      restart: unless-stopped
      # expose:
      #   - 9100
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
        - /etc/hostname:/etc/nodename
      deploy:
        mode: global
        resources:
          limits:
            memory: 128M
          reservations:
            memory: 64M

  cadvisor:
      image: braingamer/cadvisor-arm
      # container_name: monitoring_cadvisor
      privileged: true
      restart: unless-stopped
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
      devices:
        - /dev/kmsg
      # expose:
      #   - 8080
      deploy:
        mode: global
        resources:
          limits:
            memory: 128M
          reservations:
            memory: 64M

  grafana:
      image: grafana/grafana:latest
      # container_name: monitoring_grafana
      restart: unless-stopped
      links:
        - prometheus:prometheus
      # expose:
      #   - 3000
      ports:
        - 3000:3000
      volumes:
        - grafana:/var/lib/grafana
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_USERS_ALLOW_SIGN_UP=false
        # - GF_SERVER_DOMAIN=myrul.com
        - GF_SMTP_ENABLED=false
        - GF_SMTP_HOST=smtp.gmail.com:587
        - GF_SMTP_USER=myadrress@gmail.com
        - GF_SMTP_PASSWORD=mypassword
        - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
